os: linux
dist: bionic
language: c

compiler:
  - gcc

git:
  submodules: false
  depth: 3

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gpp

install:
  - wget https://github.com/vipoo/z88dk/releases/download/v2.0.0-dino.2/z88dk-v2.0.0-dino.2.tar.gz
  - mkdir -p z88dk
  - tar -xzvf z88dk-v2.0.0-dino.2.tar.gz -C ./z88dk/

before_script:
  - export PATH=`pwd`/z88dk/bin:$PATH
  - export ZCCCFG=`pwd`/z88dk/lib/config

script:
  - make VERSION=$TRAVIS_TAG
  - make test VERSION=$TRAVIS_TAG

notifications:
  email: false
